// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
///  await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBETuYq9XQkgpK-UB2CRkYVp_nV4M4dOZI',
    appId: '1:664905364299:web:1983856be218a7fda62ece',
    messagingSenderId: '664905364299',
    projectId: 'compus-9db8d',
    authDomain: 'compus-9db8d.firebaseapp.com',
    storageBucket: 'compus-9db8d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdByQCk81slWcnkuuozJuwGaJIVLCr7hc',
    appId: '1:664905364299:android:ccea40f98d586c44a62ece',
    messagingSenderId: '664905364299',
    projectId: 'compus-9db8d',
    storageBucket: 'compus-9db8d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYad1MPsZnvmxcQlV1qR0VnUXu-c9QaIY',
    appId: '1:664905364299:ios:6fc6d8a9df4e2615a62ece',
    messagingSenderId: '664905364299',
    projectId: 'compus-9db8d',
    storageBucket: 'compus-9db8d.firebasestorage.app',
    iosBundleId: 'com.example.compusConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYad1MPsZnvmxcQlV1qR0VnUXu-c9QaIY',
    appId: '1:664905364299:ios:6fc6d8a9df4e2615a62ece',
    messagingSenderId: '664905364299',
    projectId: 'compus-9db8d',
    storageBucket: 'compus-9db8d.firebasestorage.app',
    iosBundleId: 'com.example.compusConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBETuYq9XQkgpK-UB2CRkYVp_nV4M4dOZI',
    appId: '1:664905364299:web:63c4eccf192ce002a62ece',
    messagingSenderId: '664905364299',
    projectId: 'compus-9db8d',
    authDomain: 'compus-9db8d.firebaseapp.com',
    storageBucket: 'compus-9db8d.firebasestorage.app',
  );
}
